"""Mechanistic interpretability tools for Pi0.5."""

from .buffers import (
    ActivationBatch,
    ActivationBuffer,
    ActivationBufferStats,
    MultiLayerActivationBuffer,
    RunningVarianceDenominator,
    flatten_activation_record,
)
from .transcoders import (
    TimeConditionedTranscoder,
    TimeConditionedTranscoderConfig,
    TranscoderLoss,
    normalized_mse_loss,
    sinusoidal_time_embedding,
)
from .patch_pi05 import (
    ActionExpertMLPTarget,
    MLPActivationRecord,
    MLPTranscoderLatentRecord,
    MLPTranscoderTraceRecord,
    Pi05TranscoderContext,
    WrappedActionExpertMLP,
    infer_mlp_d_model,
    install_pi05_action_expert_wrappers,
    list_pi05_action_expert_mlp_targets,
)
from .feature_discovery import (
    FeatureDiscoveryCollector,
    FeatureDiscoveryConfig,
    FeatureTopK,
    RunningFeatureStats,
)
from .circuit_tracing import (
    FeatureNode,
    ParentFeatureSummary,
    TraceForwardCache,
    TraceRecord,
    aggregate_parent_contributions,
    closest_timestep_key,
    feature_key,
    load_observations,
    parse_feature_key,
    parent_summary_to_edge,
    prune_edges_by_cumulative_influence,
    prune_nodes_by_cumulative_influence,
    source_contributions_to_layers,
    source_contributions_to_target,
    node_influence_scores,
    timestep_key,
    top_examples_for_target,
    write_trace_outputs,
)

__all__ = [
    "ActionExpertMLPTarget",
    "ActivationBatch",
    "ActivationBuffer",
    "ActivationBufferStats",
    "FeatureDiscoveryCollector",
    "FeatureDiscoveryConfig",
    "FeatureNode",
    "FeatureTopK",
    "MLPActivationRecord",
    "MLPTranscoderLatentRecord",
    "MLPTranscoderTraceRecord",
    "MultiLayerActivationBuffer",
    "Pi05TranscoderContext",
    "ParentFeatureSummary",
    "RunningVarianceDenominator",
    "RunningFeatureStats",
    "TraceForwardCache",
    "TraceRecord",
    "TimeConditionedTranscoder",
    "TimeConditionedTranscoderConfig",
    "TranscoderLoss",
    "WrappedActionExpertMLP",
    "flatten_activation_record",
    "closest_timestep_key",
    "infer_mlp_d_model",
    "install_pi05_action_expert_wrappers",
    "load_observations",
    "list_pi05_action_expert_mlp_targets",
    "normalized_mse_loss",
    "parent_summary_to_edge",
    "parse_feature_key",
    "prune_edges_by_cumulative_influence",
    "prune_nodes_by_cumulative_influence",
    "sinusoidal_time_embedding",
    "source_contributions_to_layers",
    "source_contributions_to_target",
    "node_influence_scores",
    "timestep_key",
    "top_examples_for_target",
    "write_trace_outputs",
]
