"""Mechanistic interpretability tools for Pi0.5."""

from .buffers import (
    ActivationBatch,
    ActivationBuffer,
    ActivationBufferStats,
    MultiLayerActivationBuffer,
    RunningVarianceDenominator,
    flatten_activation_record,
)
from .transcoders import (
    TimeConditionedTranscoder,
    TimeConditionedTranscoderConfig,
    TranscoderLoss,
    normalized_mse_loss,
    sinusoidal_time_embedding,
)
from .patch_pi05 import (
    ActionExpertMLPTarget,
    MLPActivationRecord,
    MLPTranscoderLatentRecord,
    Pi05TranscoderContext,
    WrappedActionExpertMLP,
    infer_mlp_d_model,
    install_pi05_action_expert_wrappers,
    list_pi05_action_expert_mlp_targets,
)
from .scene_perturbation import (
    ColorPerturbation,
    SceneGeom,
    SceneObject,
    blend_geom_color,
    find_objects,
    image_delta_stats,
    list_scene_geoms,
    list_scene_objects,
    resolve_geom_ids,
    resolve_mj_model,
    set_geom_color,
    shift_geom_hue,
)
from .feature_discovery import (
    FeatureDiscoveryCollector,
    FeatureDiscoveryConfig,
    FeatureTopK,
    RunningFeatureStats,
)

__all__ = [
    "shift_geom_hue",
    "set_geom_color",
    "resolve_mj_model",
    "resolve_geom_ids",
    "list_scene_objects",
    "list_scene_geoms",
    "image_delta_stats",
    "find_objects",
    "blend_geom_color",
    "SceneObject",
    "SceneGeom",
    "ColorPerturbation",
    "ActionExpertMLPTarget",
    "ActivationBatch",
    "ActivationBuffer",
    "ActivationBufferStats",
    "FeatureDiscoveryCollector",
    "FeatureDiscoveryConfig",
    "FeatureTopK",
    "MLPActivationRecord",
    "MLPTranscoderLatentRecord",
    "MultiLayerActivationBuffer",
    "Pi05TranscoderContext",
    "RunningVarianceDenominator",
    "RunningFeatureStats",
    "TimeConditionedTranscoder",
    "TimeConditionedTranscoderConfig",
    "TranscoderLoss",
    "WrappedActionExpertMLP",
    "flatten_activation_record",
    "infer_mlp_d_model",
    "install_pi05_action_expert_wrappers",
    "list_pi05_action_expert_mlp_targets",
    "normalized_mse_loss",
    "sinusoidal_time_embedding",
]
