#!/usr/bin/env bash
set -euo pipefail

TASKS="${1:-libero_spatial}"
EPISODES="${2:-1}"
TASK_IDS="${TASK_IDS:-[0]}"
TASK_ID_FOR_VIDEO="${TASK_ID_FOR_VIDEO:-0}"
SEED="${SEED:-1000}"
STOP_AFTER="${STOP_AFTER:-0}"
CAPTURE_MAX_CHUNKS="${CAPTURE_MAX_CHUNKS:-80}"
CAPTURE_LAYER_STRIDE="${CAPTURE_LAYER_STRIDE:-1}"
CAPTURE_MAX_BINS="${CAPTURE_MAX_BINS:-64}"
CAPTURE_FAMILIES="${CAPTURE_FAMILIES:-vision,prefix,expert,projection}"
CAPTURE_PARAM_STATS="${CAPTURE_PARAM_STATS:-0}"
CAPTURE_FEEDBACK_TRACE="${CAPTURE_FEEDBACK_TRACE:-1}"
CAPTURE_ENV_STEPS="${CAPTURE_ENV_STEPS:-1}"
CAPTURE_ENV_STEP_IMAGES="${CAPTURE_ENV_STEP_IMAGES:-0}"
CAPTURE_ENV_STEP_IMAGE_EVERY_N="${CAPTURE_ENV_STEP_IMAGE_EVERY_N:-10}"
CAPTURE_MAX_ENV_STEP_IMAGES="${CAPTURE_MAX_ENV_STEP_IMAGES:-80}"
CAPTURE_TOKEN_IDS="${CAPTURE_TOKEN_IDS:-1}"
CAPTURE_DECODE_LANGUAGE="${CAPTURE_DECODE_LANGUAGE:-0}"
CAPTURE_BATCH_TENSOR_SUMMARY="${CAPTURE_BATCH_TENSOR_SUMMARY:-1}"
CAPTURE_DENOISE_TRACE="${CAPTURE_DENOISE_TRACE:-1}"
CAPTURE_MAX_TENSOR_VALUES="${CAPTURE_MAX_TENSOR_VALUES:-64}"
PI05_PROMPT_FEEDBACK_MODE="${PI05_PROMPT_FEEDBACK_MODE:-off}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

"${ROOT}/scripts/gcp_create_l4_vm.sh"

CAPTURE_ACTIVATIONS=1 \
CAPTURE_MAX_CHUNKS="${CAPTURE_MAX_CHUNKS}" \
CAPTURE_LAYER_STRIDE="${CAPTURE_LAYER_STRIDE}" \
CAPTURE_MAX_BINS="${CAPTURE_MAX_BINS}" \
CAPTURE_FAMILIES="${CAPTURE_FAMILIES}" \
CAPTURE_PARAM_STATS="${CAPTURE_PARAM_STATS}" \
CAPTURE_FEEDBACK_TRACE="${CAPTURE_FEEDBACK_TRACE}" \
CAPTURE_ENV_STEPS="${CAPTURE_ENV_STEPS}" \
CAPTURE_ENV_STEP_IMAGES="${CAPTURE_ENV_STEP_IMAGES}" \
CAPTURE_ENV_STEP_IMAGE_EVERY_N="${CAPTURE_ENV_STEP_IMAGE_EVERY_N}" \
CAPTURE_MAX_ENV_STEP_IMAGES="${CAPTURE_MAX_ENV_STEP_IMAGES}" \
CAPTURE_TOKEN_IDS="${CAPTURE_TOKEN_IDS}" \
CAPTURE_DECODE_LANGUAGE="${CAPTURE_DECODE_LANGUAGE}" \
CAPTURE_BATCH_TENSOR_SUMMARY="${CAPTURE_BATCH_TENSOR_SUMMARY}" \
CAPTURE_DENOISE_TRACE="${CAPTURE_DENOISE_TRACE}" \
CAPTURE_MAX_TENSOR_VALUES="${CAPTURE_MAX_TENSOR_VALUES}" \
PI05_PROMPT_FEEDBACK_MODE="${PI05_PROMPT_FEEDBACK_MODE}" \
SEED="${SEED}" \
TASK_IDS="${TASK_IDS}" \
"${ROOT}/scripts/gcp_run_pi05_libero_uv.sh" "${TASKS}" "${EPISODES}"

"${ROOT}/scripts/gcp_fetch_pi05_results.sh" latest
"${ROOT}/scripts/summarize_pi05_feedback_trace.py" --run latest --max-steps 80
"${ROOT}/scripts/make_pi05_analysis_video.py" --run latest --task-id "${TASK_ID_FOR_VIDEO}" --open

if [[ "${STOP_AFTER}" == "1" ]]; then
  gcloud compute instances stop "${VM_NAME:-lerobot-libero-l4}" \
    --project="${PROJECT:-breadwinner-415122}" \
    --zone="${ZONE:-us-central1-a}" \
    --quiet
fi
